blank_issues_enabled: false
contact_links:
  - name: Ask a question / Discussion
    url: https://github.com/amansrivastava17/slackhive/discussions
    about: Use GitHub Discussions for questions, ideas, and show-and-tell
