/**
 * @fileoverview REST API route for agent collection operations.
 *
 * GET  /api/agents — List all agents
 * POST /api/agents — Create a new agent
 *
 * @module web/api/agents
 */

import { NextRequest, NextResponse } from 'next/server';
import { apiError } from '@/lib/api-error';
import {
  getAllAgents,
  createAgent,
  setAgentMcps,
  upsertSkill,
  upsertPermissions,
  publishAgentEvent,
  applyLiveStatus,
  listAccessibleAgentIds,
  listWritableAgentIds,
  getMcpServerById,
} from '@/lib/db';
import type { CreateAgentRequest } from '@slackhive/shared';
import { SKILL_TEMPLATES } from '@/lib/skill-templates';
import { regenerateBossRegistry } from '@/lib/boss-registry';
import { guardAdmin } from '@/lib/api-guard';
import { getSessionFromRequest } from '@/lib/auth';
import { toAgentPublic } from '@/lib/agent-public';

export const dynamic = 'force-dynamic';

/**
 * GET /api/agents
 * Returns all registered agents ordered boss-first.
 *
 * @returns {Promise<NextResponse>} JSON array of Agent objects.
 */
export async function GET(req: NextRequest): Promise<NextResponse> {
  try {
    const session = getSessionFromRequest(req);
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    const agents = await getAllAgents();
    const writableOnly = req.nextUrl.searchParams.get('writable') === 'true';
    const accessibleIds = writableOnly
      ? await listWritableAgentIds(session.username, session.role)
      : await listAccessibleAgentIds(session.username, session.role);
    const visible = accessibleIds === null ? agents : agents.filter(a => accessibleIds!.includes(a.id));
    return NextResponse.json(visible.map(a => toAgentPublic(applyLiveStatus(a))));
  } catch (err) {
    return apiError('agents', err);
  }
}

/**
 * POST /api/agents
 * Creates a new agent with its initial configuration.
 * Also bootstraps skills from a template and assigns MCPs.
 * Publishes a start event so the runner picks it up immediately.
 *
 * @param {NextRequest} request - Request body matching CreateAgentRequest.
 * @returns {Promise<NextResponse>} The created Agent (201), or error.
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  const denied = guardAdmin(request);
  if (denied) return denied;
  try {
    const body = (await request.json()) as CreateAgentRequest;

    // Validate required fields. Description is required for non-boss agents so the
    // Coach bootstrap seed is always non-empty and CLAUDE.md has a real identity.
    // Boss agents get auto-generated CLAUDE.md from boss-registry, so description is optional.
    if (!body.slug || !body.name) {
      return NextResponse.json(
        { error: 'slug and name are required' },
        { status: 400 }
      );
    }
    if (!body.isBoss && !body.description?.trim()) {
      return NextResponse.json(
        { error: 'description is required' },
        { status: 400 }
      );
    }

    const session = getSessionFromRequest(request);

    // MCP ownership check — same policy as PUT /api/agents/[id]/mcps:
    // editors can only assign MCPs they own; admins/superadmins bypass. Without
    // this an editor could attach another editor's private MCP to a freshly
    // created agent and silently use its credentials. Rejected with 403 so the
    // user sees the violation explicitly rather than a silent drop.
    const isAdmin = session?.role === 'admin' || session?.role === 'superadmin';
    if (!isAdmin && body.mcpServerIds?.length) {
      const mcps = await Promise.all(body.mcpServerIds.map(mid => getMcpServerById(mid)));
      const unauthorized = mcps.find(m => m && m.createdBy !== session?.username);
      if (unauthorized) {
        return NextResponse.json(
          { error: `Only the MCP owner or an admin can assign "${unauthorized.name}"` },
          { status: 403 },
        );
      }
    }

    // Create the agent record, tracking who created it
    const agent = await createAgent(body, session?.username ?? 'system');

    // Assign MCPs if provided
    if (body.mcpServerIds?.length) {
      await setAgentMcps(agent.id, body.mcpServerIds);
    }

    // Boss agents skip skill template — their CLAUDE.md is auto-generated by boss-registry
    if (!agent.isBoss) {
      const template = body.skillTemplate ?? 'blank';
      const skills = SKILL_TEMPLATES[template](agent);
      for (const skill of skills) {
        await upsertSkill(agent.id, skill.category, skill.filename, skill.content, skill.sortOrder);
      }
    }

    // Create default permissions — safe tools for file access + code search
    const allowedTools = ['Read', 'Write', 'Edit', 'Glob', 'Grep'];
    await upsertPermissions(agent.id, allowedTools, []);

    // Signal the runner to start this agent
    await publishAgentEvent({ type: 'start', agentId: agent.id });

    // Regenerate boss registry now that team has a new member
    await regenerateBossRegistry().catch(() => {});

    return NextResponse.json(toAgentPublic(agent), { status: 201 });
  } catch (err) {
    if ((err as Error).message?.includes('unique')) {
      return NextResponse.json({ error: 'An agent with this slug already exists' }, { status: 409 });
    }
    return apiError('agents POST', err);
  }
}
