/**
 * @fileoverview `slackhive init` — clone, configure, and start SlackHive.
 *
 * @module cli/commands/init
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import chalk from 'chalk';
import ora from 'ora';
import prompts from 'prompts';

const REPO_URL = 'https://github.com/pelago-labs/slackhive.git';

interface InitOptions {
  dir: string;
  skipStart?: boolean;
}

/**
 * Runs `slackhive init` — interactive setup wizard.
 *
 * @param {InitOptions} opts - CLI options.
 */
export async function init(opts: InitOptions): Promise<void> {
  const dir = resolve(opts.dir);

  const O = chalk.hex('#D97757').bold;
  const W = chalk.hex('#EBE6E0').bold;
  console.log('');
  console.log('      ' + W('│   │'));
  console.log('   ' + W('───┼───┼───'));
  console.log('  ' + O('>') + W(' ──┼──') + O('█') + W('┼──'));
  console.log('      ' + W('│   │'));
  console.log('');
  console.log(chalk.bold('  SlackHive') + chalk.gray(' — AI agent teams on Slack'));
  console.log('');

  // ── Step 1: Check prerequisites ───────────────────────────────────────────
  console.log(chalk.bold.hex('#D97757')('  [1/4]') + chalk.bold(' Checking prerequisites'));
  console.log('');

  const needsClone = !existsSync(dir);
  const checks = [
    { name: 'Node.js', cmd: 'node --version', errMsg: 'Node.js not found. Please install Node.js 20+ first.' },
    ...(needsClone ? [{ name: 'Git', cmd: 'git --version', errMsg: 'Git not found. Install Git or download SlackHive manually.' }] : []),
  ];

  for (const check of checks) {
    const spinner = ora(`  Checking ${check.name}...`).start();
    try {
      execSync(check.cmd, { stdio: 'ignore' });
      spinner.succeed(chalk.green(`${check.name} ready`));
    } catch {
      spinner.fail(chalk.red(`${check.name}: ${check.errMsg}`));
      process.exit(1);
    }
  }
  console.log('');

  // ── Step 2: Clone ─────────────────────────────────────────────────────────
  console.log(chalk.bold.hex('#D97757')('  [2/4]') + chalk.bold(' Getting SlackHive'));
  console.log('');

  if (existsSync(dir)) {
    console.log(chalk.yellow(`  note: Directory ${opts.dir} already exists — using existing`));
  } else {
    const spinner = ora('  Cloning repository...').start();
    try {
      execSync(`git clone --depth 1 ${REPO_URL} "${dir}"`, { stdio: 'ignore' });
      spinner.succeed('Repository cloned');
    } catch {
      spinner.fail('Failed to clone repository');
      process.exit(1);
    }
  }
  console.log('');

  // ── Step 3: Configure .env ────────────────────────────────────────────────
  const envPath = join(dir, '.env');
  const freshEnv = !existsSync(envPath);

  if (freshEnv) {
    console.log(chalk.bold.hex('#D97757')('  [3/4]') + chalk.bold(' Configure environment'));
    console.log('');

    // Agent backend (Claude Code / Codex) and its credentials are now configured
    // in the web UI under Settings → Agent Backend — no longer prompted here.
    console.log(chalk.gray('  Agent backend & credentials (Claude Code or Codex) are configured'));
    console.log(chalk.gray('  in the web UI: Settings → Agent Backend, after first launch.'));
    console.log('');

    const response = await prompts([
      { type: 'text', name: 'adminUsername', message: 'Admin username', initial: 'admin' },
      { type: 'password', name: 'adminPassword', message: 'Admin password', validate: (v: string) => v.length >= 6 ? true : 'At least 6 characters' },
    ]);

    if (!response.adminPassword) {
      console.log(chalk.red('\n  Setup cancelled.'));
      process.exit(1);
    }

    let envContent = '# Generated by slackhive init\n\n';
    envContent += `# Agent backend auth (Claude Code / Codex) is configured in Settings → Agent Backend\n`;

    envContent += `\n# SQLite, no Docker required\n`;
    envContent += `DATABASE_TYPE=sqlite\n`;

    envContent += `\nADMIN_USERNAME=${response.adminUsername}\n`;
    envContent += `ADMIN_PASSWORD=${response.adminPassword}\n`;
    envContent += `AUTH_SECRET=${randomSecret()}\n`;
    envContent += `ENV_SECRET_KEY=${randomSecret()}\n`;
    envContent += `\nNODE_ENV=production\n`;

    writeFileSync(envPath, envContent);
    console.log('');
    console.log(chalk.green('  ✓') + ' .env file created');
    console.log('');
  } else {
    console.log(chalk.bold.hex('#D97757')('  [3/4]') + chalk.bold(' Configure environment'));
    console.log('');
    // Check if existing .env is missing required keys
    let envContents = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : '';
    const missingKeys: string[] = [];
    if (!envContents.includes('AUTH_SECRET=')) missingKeys.push('AUTH_SECRET');
    if (!envContents.includes('ENV_SECRET_KEY=')) missingKeys.push('ENV_SECRET_KEY');
    if (missingKeys.length > 0) {
      console.log(chalk.yellow(`  warning: .env is missing: ${missingKeys.join(', ')} — patching...`));
      let patch = '';
      if (!envContents.includes('AUTH_SECRET=')) patch += `AUTH_SECRET=${randomSecret()}\n`;
      if (!envContents.includes('ENV_SECRET_KEY=')) patch += `ENV_SECRET_KEY=${randomSecret()}\n`;
      require('fs').appendFileSync(envPath, patch);
      envContents = readFileSync(envPath, 'utf-8');
      console.log(chalk.green('  ✓') + ' .env patched');
    }

    console.log(chalk.yellow('  note: .env already exists — skipping configuration'));
    console.log(chalk.gray('  Agent backend auth (Claude Code or Codex) is managed in Settings → Agent Backend.'));
    console.log('');
  }

  // ── Step 4: Build & start ─────────────────────────────────────────────────
  let webReady = true;
  if (!opts.skipStart) {
    console.log(chalk.bold.hex('#D97757')('  [4/4]') + chalk.bold(' Installing & starting'));
    console.log(chalk.gray('  Installing dependencies and building TypeScript...'));
    console.log('');

    // Create native mode marker file
    writeFileSync(join(dir, '.slackhive-native'), 'native');

    const installSpinner = ora('  Installing npm dependencies...').start();
    try {
      execSync('npm install', { cwd: dir, stdio: 'ignore', timeout: 180000 });
      installSpinner.succeed('Dependencies installed');
    } catch (err) {
      installSpinner.fail('npm install failed');
      console.log(chalk.red(`  ${(err as Error).message}`));
      webReady = false;
    }

    if (webReady) {
      const buildSpinner = ora('  Building TypeScript...').start();
      try {
        execSync('npm run build -w packages/shared -w cli && npx tsc --project apps/runner/tsconfig.json --skipLibCheck', { cwd: dir, stdio: 'ignore', timeout: 120000 });
        buildSpinner.succeed('Build complete');
      } catch (err) {
        buildSpinner.fail('Build failed');
        console.log(chalk.red(`  ${(err as Error).message}`));
        webReady = false;
      }
    }

    if (webReady) {
      // Build Next.js
      const nextSpinner = ora('  Building Next.js web app...').start();
      try {
        // Load env vars for the Next.js build
        const envPath = join(dir, '.env');
        const envVars: Record<string, string> = { ...process.env as Record<string, string> };
        if (existsSync(envPath)) {
          for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
            const t = line.trim();
            if (!t || t.startsWith('#')) continue;
            const eq = t.indexOf('=');
            if (eq > 0) envVars[t.slice(0, eq)] = t.slice(eq + 1);
          }
        }
        execSync('npx next build', {
          cwd: join(dir, 'apps', 'web'),
          stdio: 'ignore',
          timeout: 300000,
          env: envVars,
        });
        nextSpinner.succeed('Web app built');
      } catch (err) {
        nextSpinner.fail('Next.js build failed');
        console.log(chalk.red(`  ${(err as Error).message}`));
        webReady = false;
      }
    }

    // Start in native mode
    if (webReady) {
      try {
        process.chdir(dir);
        const manage = require('./manage');
        await manage.start();
      } catch (err) {
        console.log(chalk.yellow(`  Auto-start failed — run \`slackhive start\` manually (${(err as Error).message})`));
        webReady = false;
      }
    }
  }

  // ── Done ──────────────────────────────────────────────────────────────────
  console.log('');
  if (webReady) {
    console.log('  ' + chalk.bgHex('#D97757').black.bold('  SlackHive is ready!  '));
    console.log('');
    console.log(`  ${chalk.bold('Open:')}     ${chalk.cyan(`http://localhost:${process.env.PORT ?? '3001'}`)}`);
  } else {
    console.log('  ' + chalk.bold('Setup complete!'));
    console.log('');
    console.log(chalk.gray('  Services are still starting. Once ready:'));
    console.log(`  ${chalk.bold('Run:')}      ${chalk.cyan('slackhive start')}`);
    console.log(`  ${chalk.bold('Open:')}     ${chalk.cyan(`http://localhost:${process.env.PORT ?? '3001'}`)}`);
  }
  console.log(`  ${chalk.bold('Dir:')}      ${chalk.gray(dir)}`);
  console.log(`  ${chalk.bold('Mode:')}     ${chalk.gray('Native (SQLite)')}`);
  const home = process.env.HOME ?? process.env.USERPROFILE ?? '/tmp';
  console.log(`  ${chalk.bold('Database:')} ${chalk.gray(join(home, '.slackhive', 'data.db'))}`);
  console.log(`  ${chalk.bold('Logs:')}     ${chalk.gray(join(home, '.slackhive', 'logs', 'runner.log'))}`);

  console.log('');
  console.log(chalk.gray('  Useful commands:'));
  console.log(chalk.gray('    slackhive start    — Start services'));
  console.log(chalk.gray('    slackhive stop     — Stop services'));
  console.log(chalk.gray('    slackhive status   — Show container status'));
  console.log(chalk.gray('    slackhive logs     — Tail runner logs'));
  console.log(chalk.gray('    slackhive update   — Pull latest & rebuild'));
  console.log('');
}

function randomSecret(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 32; i++) result += chars.charAt(Math.floor(Math.random() * chars.length));
  return result;
}

